name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool
      - name: Generate configure script
        run: |
            cd 'AddressBook-NewDesign copy'
            autoreconf -i
      - name: Configure
        run: |
            cd 'AddressBook-NewDesign copy'
            ./configure
      - name: Build
        run: |
            cd 'AddressBook-NewDesign copy'
            make
      - name: Run the program
        run: |
            cd 'AddressBook-NewDesign copy'
            ./my_program